version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y git g++ cmake libsfml-dev libxrandr-dev libxcursor-dev libudev-dev libfreetype-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev
      - run:
          name: Configure and Build and Test
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            name: Test Executable
            command: ./build/PacManGame
            when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
