version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y g++ cmake libsfml-dev libxrandr-dev libxcursor-dev libudev-dev libfreetype-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev
      - run:
          name: Configure
          command: mkdir build && cd build && cmake ..
      - run:
          name: Build
          command: cmake --build . --config Release
      - run:
          name: Test Executable
          command: ./bin/PacManGame

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
